default:
  global: 
    root: '.'
    domain: 'test.flagged.download'

    dns: 'cloudflare'
    fs: 'google'
    cdn: 'cloudflare'

  providers:
    google:
      keyfile: './google-auth.json'
      project-id: 'alien-sol-165018'