default:
  root: '.'


# providers:
#   google:
#     project-id: "wise-arena-231723"

  

# production:
#   key: 'XXX'
#   secret: 'XXX'
#   domain: 'eager.io'

# development:
#   key: 'XXX'
#   secret: 'XXX'
#   domain: 'next.eager.io'